#!/usr/bin/env bash

if
  [[ -s "/home/cabox/.rvm/gems/ruby-2.3.4/environment" ]]
then
  source "/home/cabox/.rvm/gems/ruby-2.3.4/environment"
  exec erubis "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/cabox/.rvm/gems/ruby-2.3.4/environment'" >&2
  exit 1
fi
