#!/usr/bin/env bash

if
  [[ -s "/home/cabox/.rvm/gems/ruby-2.1.2@global/environment" ]]
then
  source "/home/cabox/.rvm/gems/ruby-2.1.2@global/environment"
  exec ruby "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/cabox/.rvm/gems/ruby-2.1.2@global/environment'" >&2
  exit 1
fi
