#!/usr/bin/env bash

if
  [[ -s "/home/cabox/.rvm/gems/ruby-2.3.4@global/environment" ]]
then
  source "/home/cabox/.rvm/gems/ruby-2.3.4@global/environment"
  exec bundler "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/cabox/.rvm/gems/ruby-2.3.4@global/environment'" >&2
  exit 1
fi
